### ISSUE TITLE
Getting "type not supported as root type by protobuf" for serialization of short and UUID types

### ISSUE THREAD

**Issue by eldadru** [FasterXML/jackson-dataformats-binary#68] opened 2017-03-28 07:52 UTC
Hi,

I'm trying to serialize to following class to protobuf using jackson dataformats:

```java
public class HeaderTest
{
  @JsonProperty("version")
  private short version;
  @JsonProperty("messageId")
  private UUID messageId;


  public HeaderTest(short version, UUID messageId)
  {
    this.messageId = messageId;
    this.version = version;
  }
  public short getVersion() {
    return version;
  }

  public void setVersion(short version) {
    this.version = version;
  }

  public UUID getMessageId() {
    return messageId;
  }

  public void setMessageId(UUID messageId) {
    this.messageId = messageId;
  }
}
```

With the following code:

    ProtobufMapper mapper = new ProtobufMapper();
    **ProtobufSchema schemaWrapper = mapper.generateSchemaFor(HeaderTest.class);**
    NativeProtobufSchema nativeProtobufSchema = schemaWrapper.getSource();
    String asProtofile = nativeProtobufSchema.toString();

The bold line throws this exception:

```
java.lang.UnsupportedOperationException: 'Integer' type not supported as root type by protobuf

	at com.fasterxml.jackson.dataformat.protobuf.schemagen.ProtoBufSchemaVisitor._throwUnsupported(ProtoBufSchemaVisitor.java:141)
	at com.fasterxml.jackson.dataformat.protobuf.schemagen.ProtoBufSchemaVisitor.expectIntegerFormat(ProtoBufSchemaVisitor.java:112)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.visitIntFormat(StdSerializer.java:215)
	at com.fasterxml.jackson.databind.ser.std.NumberSerializers$Base.acceptJsonFormatVisitor(NumberSerializers.java:75)
	at com.fasterxml.jackson.databind.ser.std.NumberSerializers$ShortSerializer.acceptJsonFormatVisitor(NumberSerializers.java:103)
	at com.fasterxml.jackson.dataformat.protobuf.schemagen.ProtobuffSchemaHelper.acceptTypeElement(ProtobuffSchemaHelper.java:49)
	at com.fasterxml.jackson.dataformat.protobuf.schemagen.MessageElementVisitor.getDataType(MessageElementVisitor.java:122)
	at com.fasterxml.jackson.dataformat.protobuf.schemagen.MessageElementVisitor.buildFieldElement(MessageElementVisitor.java:86)
	at com.fasterxml.jackson.dataformat.protobuf.schemagen.MessageElementVisitor.optionalProperty(MessageElementVisitor.java:65)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:805)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:833)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:580)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3641)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:3620)
	at com.fasterxml.jackson.dataformat.protobuf.ProtobufMapper.generateSchemaFor(ProtobufMapper.java:95)
```

Any ideas why I can't serialize those types? I couldn't find any online resource about that issue.

Thanks

**Comment by cowtowncoder** [comment] 2017-03-28 19:29
I can't say off-hand what could be causing this. Which version is this with?

**Comment by eldadru** [comment] 2017-03-28 19:33
Currently, 2.8.1 but also tried the latest version 2.9.0.pr2

**Comment by cowtowncoder** [comment] 2017-03-28 19:36
@eldadru then it probably exists in 2.8.7 too. If easy enough would be nice to double-check, but if not this is fine.

**Comment by eldadru** [comment] 2017-03-29 08:43
Sorry, I already refactored the code

**Comment by cowtowncoder** [comment] 2017-03-29 22:14
@eldadru that's ok, I should be able to reproduce this easily.

**Comment by cowtowncoder** [comment] 2017-03-29 22:26
Yes, I can reproduce this. Should work, not sure yet why it does not.

**Comment by cowtowncoder** [comment] 2017-03-29 23:31
Ok. Fixing may take a while since this is part of code I did not write (it's a contribution), and some of the logic is bit difficult to follow. Fix for `short` is relatively easy (it just needs to be handled like `int`, basically). And in theory `UUID` and similar types really should be handled as either `String`, or, perhaps, byte array (since format supports native binary content).
But for some reason current schema generator is pickier...

**Comment by cowtowncoder** [comment] 2017-04-01 04:57
There was a bit bigger issue, but things should work significantly better after fix. Will be in 2.9.0.pr3.

**Closed** 2017-04-01 04:57 UTC
Labels: protobuf

**Comment by eldadru** [comment] 2017-04-01 06:16
@cowtowncoder Thanks!

**Comment by cowtowncoder** [comment] 2017-04-03 16:46
@eldadru Thank you for reporting this: handling was basically wrong and could only support a small number of primitives, regular POJOs and Lists/arrays. What needed to be added was actual handling of typing as indicated by callbacks, so that (for example) date/time values are indicate as types that they would be encoded in JSON (if written as textual timestamps, then String, if `long` timestamps, 64-bit and so on).

I suspect there may some other rough edges but I hope these can be located and fixed over time as well.
