### ISSUE TITLE
Some short UTF Strings encoded using non-canonical form

### ISSUE THREAD

**Issue by Sajjon** [FasterXML/jackson-dataformats-binary#159] opened 2019-04-22 08:31 UTC
Hey!

I recently discovered that Jackson produces UTF strings on the non-shortest-possible format (non-canonical form ) sometimes.

I first reported [this issue CBOR Github](https://github.com/cbor/cbor.github.io/issues/49) but realized that most other CBOR project is using canonical form where Jackson is not.

It would be great if you could support canonical encoding of strings :)

**Comment by cabo** [comment] 2019-04-22 11:34
Note that this bug report is not about the missing feature of generating "canonical" encoding (which would be a duplicate of #138), but about a set of off-by-one errors in the basic encoding logic which seem to lead to valid, but unnecessarily long encoding for ASCII strings of length 23 and 255.  Please see the [referenced issue](https://github.com/cbor/cbor.github.io/issues/49) for details.  I'm not claiming to have read the entirety of CBORGenerator.java, but it seems that Line 1251 is not the only place that has this off-by-one error (maybe search for lines with `...MAX...` that have `<` instead of `<=`).

**Comment by cowtowncoder** [comment] 2019-04-22 17:24
@Sajjon thank you for reporting this.
@cabo thank you for clarification: that does make more sense. I'll update the title.

**Comment by cowtowncoder** [comment] 2019-04-22 17:27
Added this on 

https://github.com/FasterXML/jackson-future-ideas/wiki/Jackson-Work-in-Progress

and hopefully include in 2.10 (depending on fix, could consider 2.9 backport but bit worried that change not safe for patch as 2.9 is quite far along patch series -- while correction, change to encoded data length can probably trigger bogus test fails in downstream deps).

**Comment by Sajjon** [comment] 2019-04-23 07:33
@cowtowncoder @cabo Great job guys! Thanks a lot for your prompt reply. Looking forward to the fix!

**Closed** 2019-05-07 04:03 UTC
Labels: 2.9, active, cbor

**Comment by cowtowncoder** [comment] 2019-05-11 17:24
Hoping to get 2.9.9 out Real Soon Now -- just received a potential CVE, which I'll need to address, but after that.

**Comment by Sajjon** [comment] 2019-05-12 19:03
Great job! 💪

**Comment by cowtowncoder** [comment] 2019-05-13 01:04
@Sajjon thank you once again for reporting this -- we take correctness and interoperability seriously, so it's good to weed out these deviations at least eventually over time :)
